global:
  scrape_interval: 15s

scrape_configs:
  # Meshtastic : exporter Prometheus officiel (consomme le MQTT, expose /metrics sur 9464)
  - job_name: 'meshtastic'
    static_configs:
      - targets: ['meshtastic-exporter:9464']

  # ESP32 : carte Heltec qui expose ses métriques en HTTP
  - job_name: 'esp32'
    static_configs:
      - targets: ['192.168.1.155:80']
    metrics_path: '/metrics'